# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Llmtop < Formula
  desc "htop for your LLM inference cluster — real-time dashboard for vLLM, SGLang, LMCache, NIM with GPU monitoring"
  homepage "https://github.com/InfraWhisperer/llmtop"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/InfraWhisperer/llmtop/releases/download/v0.1.0/llmtop_0.1.0_darwin_amd64.tar.gz"
      sha256 "951b52f78bb71fd8f991b9aea5a8cf2105fdc3c19cf12f32cadd6dc3bc9a68a8"

      define_method(:install) do
        bin.install "llmtop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/InfraWhisperer/llmtop/releases/download/v0.1.0/llmtop_0.1.0_darwin_arm64.tar.gz"
      sha256 "5d890e1dce651e729d6d89f9278990102dd5d4e2566b20b2add9631d0a288719"

      define_method(:install) do
        bin.install "llmtop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/InfraWhisperer/llmtop/releases/download/v0.1.0/llmtop_0.1.0_linux_amd64.tar.gz"
      sha256 "4f5d8b48307e178067f13b1123d5f3cf82ab90b5fb28131e275ea523d1cb13a2"
      define_method(:install) do
        bin.install "llmtop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/InfraWhisperer/llmtop/releases/download/v0.1.0/llmtop_0.1.0_linux_arm64.tar.gz"
      sha256 "37f8371c31d654fd392ef9c4af82125c0e322a9aa4c3e7d73ad18ce611984f6f"
      define_method(:install) do
        bin.install "llmtop"
      end
    end
  end

  test do
    system "#{bin}/llmtop", "version"
  end
end
